### PR TITLE
Removed unused crates from example

### PR DESCRIPTION
**Pull request by Byron**
Additionally, vsync was enabled for the window which improves quality
of the fast rotating rectangles.

### CODE REVIEW

**Comment by bvssvni** [comment]
One can use `.ext_dt` from `RenderArgs` to smooth the animation instead of enabling vsync. There is an example of this here https://github.com/PistonDevelopers/piston-examples/blob/master/src/cube.rs#L157.

**Comment by Byron** [comment]
And I thought vsync is responsible for syncing the frame drawing with the vertical speed of your output device to prevent smearing effects.
Would you like me to turn it off, and maybe use `.ext_dt` instead ?

**Comment by bvssvni** [comment]
You are right about vsync. I suggested `.ext_dt` as an alternative way of improving the quality.

**Comment by Byron** [comment]
Ah, ok. I can't really get into .ext_dt, as it seems to be quite a different delta-time. Also it's not that the animation is choppy, it just smeared a little (similar to how the shooter example does when moving the player head horizontally).
Is there anything else you'd like me to change before merging ?

**Comment by bvssvni** [comment]
I believe you can remove the dependency on gfx_graphics, now that `Glyphs` is used instead.

**Comment by Byron** [comment]
Done ! Much better !

**Comment by bvssvni** [comment]
Looks good now! Merging.

**Comment by mitchmindtree** [comment]
Thank you both! :)

**Pull request merged**
